spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/newdb
    username: root
    password: Develhope10.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop

---
profiles:
  active: prod
server:
  port: 5000
welcomeMsg: Hello form Prod

---
profiles:
  active: test
server:
  port: 4000
welcomeMsg: Hello form Test